"""
Flat plate / shell element 2-D surface mesh generator (FAHTS approach).

Creates Quad4 shell elements tiling the face of a QUADSHEL structural element.
The 2-D heat equation is solved in the plane of the plate; wall thickness is
a scalar parameter (SINTEF FAHTS §3.2.2).

Default mesh divisions (matching FAHTS software defaults):
    mesh_12 = 4   elements along the n1 → n2 edge direction
    mesh_14 = 2   elements along the n1 → n4 edge direction

Node positions are generated by bilinear interpolation between the four corner
positions P1, P2, P3, P4 (global 3-D coordinates of QUADSHEL nodes n1–n4).
The 2-D local FEM coordinates are obtained by projecting onto the plate's
local basis:
    e1 = normalise(P2 − P1)               (along n1→n2)
    n  = normalise(cross(P2−P1, P4−P1))   (plate normal)
    e2 = cross(n, e1)                     (in-plane, perpendicular to e1)

For TRISHELL elements (3 nodes) the surface mesh approach is not applied;
the caller should fall back to the 1-D Shell1DSolver for those elements.
"""
from __future__ import annotations

import numpy as np

from fahts.core.model.section import PlateSection
from .beam_surface_mesh import BeamSurfaceMesh


class PlateSurfaceMesher:
    """
    Generates the FAHTS-style surface Quad4 mesh for a flat plate element.

    Args:
        section:  PlateSection providing the wall thickness.
        corners:  (4, 3) global positions of nodes n1, n2, n3, n4 [m].
                  Node ordering follows USFOS QUADSHEL convention (CCW or CW
                  in the plane of the plate).
        mesh_12:  Elements along n1 → n2 direction (default 4).
        mesh_14:  Elements along n1 → n4 direction (default 2).
    """

    _DEFAULT_MESH_12 = 4
    _DEFAULT_MESH_14 = 2

    def __init__(
        self,
        section: PlateSection,
        corners: np.ndarray,
        mesh_12: int = _DEFAULT_MESH_12,
        mesh_14: int = _DEFAULT_MESH_14,
    ) -> None:
        corners = np.asarray(corners, dtype=float)
        if corners.shape != (4, 3):
            raise ValueError(
                f"corners must be shape (4, 3), got {corners.shape}"
            )
        if mesh_12 < 1:
            raise ValueError(f"mesh_12 must be >= 1, got {mesh_12}")
        if mesh_14 < 1:
            raise ValueError(f"mesh_14 must be >= 1, got {mesh_14}")
        self._sec     = section
        self._corners = corners
        self._m12     = mesh_12
        self._m14     = mesh_14

    # ── Public API ────────────────────────────────────────────────────────────

    def build(self) -> BeamSurfaceMesh:
        """Build and return the BeamSurfaceMesh for the plate element."""
        P1, P2, P3, P4 = self._corners
        m12 = self._m12
        m14 = self._m14
        t   = self._sec.thickness

        # ── Local 2-D basis ───────────────────────────────────────────────────
        v12 = P2 - P1
        v14 = P4 - P1
        e1 = v12 / np.linalg.norm(v12)
        n  = np.cross(e1, v14)
        n_norm = np.linalg.norm(n)
        if n_norm < 1e-12:
            raise ValueError(
                "Degenerate plate element: nodes are collinear or too close."
            )
        n  /= n_norm
        e2 = np.cross(n, e1)

        # ── 3-D node grid via bilinear interpolation ──────────────────────────
        # P(xi, eta) = (1-xi)(1-eta)P1 + xi(1-eta)P2 + xi*eta*P3 + (1-xi)*eta*P4
        # xi  = j / m12   (along n1→n2)
        # eta = i / m14   (along n1→n4)
        n_nodes = (m14 + 1) * (m12 + 1)
        nodes_3d = np.zeros((n_nodes, 3))

        def node_idx(i: int, j: int) -> int:
            return i * (m12 + 1) + j

        for i in range(m14 + 1):
            for j in range(m12 + 1):
                xi  = j / m12
                eta = i / m14
                P = ((1 - xi) * (1 - eta) * P1
                     + xi * (1 - eta) * P2
                     + xi * eta * P3
                     + (1 - xi) * eta * P4)
                nodes_3d[node_idx(i, j)] = P

        # ── 2-D local coordinates (project onto plate basis) ─────────────────
        n_quads = m14 * m12
        quads          = np.zeros((n_quads, 4), dtype=np.intp)
        thicknesses    = np.full(n_quads, t, dtype=float)
        local_cols_arr = np.zeros((n_quads, 2), dtype=np.intp)   # unused
        local_coords   = np.zeros((n_quads, 4, 2), dtype=float)

        q = 0
        for i in range(m14):
            for j in range(m12):
                n00 = node_idx(i,     j)
                n10 = node_idx(i + 1, j)
                n11 = node_idx(i + 1, j + 1)
                n01 = node_idx(i,     j + 1)
                quads[q] = [n00, n01, n11, n10]  # CCW when viewed from +normal

                for k, nid in enumerate([n00, n01, n11, n10]):
                    v = nodes_3d[nid] - P1
                    local_coords[q, k] = [float(np.dot(v, e1)),
                                          float(np.dot(v, e2))]
                q += 1

        return BeamSurfaceMesh(
            nodes=nodes_3d,
            quads=quads,
            thicknesses=thicknesses,
            local_cols=local_cols_arr,
            local_coords_2d=local_coords,
        )
